### ISSUE TITLE
Failed to get tweet information when downloading MP4 and GIF

### ISSUE THREAD

**Issue by SmallerDragons** [furyutei/twMediaDownloader#119]
To recreate this issue, Find any Gif or Video
Select the MP4 button beneath the tweet or window
You will be presented with "Twitter.com says: Failed to get tweet information !"
Only MP4 download button is broken right now, all other features appear to work like normal.

Have tried with fresh install Chrome, and Edge on seperare computer, yields same results, have not tested further.

## Example:
![Screenshot 2023-07-10 214309](https://github.com/furyutei/twMediaDownloader/assets/88168639/2cb09e14-6ccf-4c9f-8d02-f70f9bd85c63)

**Comment by StormTetris** [comment]
It is probably due to Twitter's API changes. Other video downloaders like [TwitterVideoDownloader](https://twittervideodownloader.com/ ) work, hopefully, this extension gets updated to fix the API problem. Images for some reason still work.
