### ISSUE TITLE
Download video error

### ISSUE THREAD

**Issue by shzxm** [furyutei/twMediaDownloader#23]
Download video error
unable to download
Authentication required cannot be used
![image](https://user-images.githubusercontent.com/9905297/68041610-e762f300-fd0b-11e9-8974-cdb2a9106ac3.png)

**Comment by ian-coog** [comment]
Confirmed, after updating to Vivaldi 2.9.1732.13 / Chrome 79.0.3945.27
Seems related to Chrome 79
