### ISSUE TITLE
Download button not showing up.

### ISSUE THREAD

**Issue by thakyZ** [furyutei/twMediaDownloader#34]
Just got on twitter this morning, found that the download button stopped showing up since yesterday.
I thought I'd just send you this bug report with an image for an example.
![image](https://user-images.githubusercontent.com/950594/79689797-e9623500-820b-11ea-8128-b9c141929282.png)

**Comment by jcchikikomori** [comment]
In my case, all of the functions has been gone since now except `Mentions` button

**Comment by jcchikikomori** [comment]
@thakyZ this issue was already fixed on version `0.1.4.6`

Please confirm on your instance, to close this

**Comment by thakyZ** [comment]
It works.
