### ISSUE TITLE
Can't download before this date

### ISSUE THREAD

**Issue by shortyseven0324** [furyutei/twMediaDownloader#44]
I can't seem to download medias/contents before this date: 19/04/2019 
From this account: https://twitter.com/iudeft0516

**Comment by furyutei** [comment]
That's probably an issue on Twitter's side.
The API for retrieving a user's timeline only allows for a maximum of 3200 tweets, so before that, I've switched internally to retrieving the search timeline.
But, [@iudeft0516](https://twitter.com/iudeft0516) account seems not be searchable for tweets prior to 2019-04-19.
[Search results before 2019-04-18T10:06:41Z on official Twitter](https://twitter.com/search?q=from%3Aiudeft0516%20until%3A2019-04-18_10%3A06%3A41_GMT&f=live)
It seems to be probably a glitch in Twitter indexing.
Please understand that this is an issue that the extension can't do anything about.

**Comment by furyutei** [comment]
It's not possible to support it on the extension side, so I'll close this issue.
