### ISSUE TITLE
[Suggestion] use /2/timeline/media API endpoint to download media only for a user

### ISSUE THREAD

**Issue by fireattack** [furyutei/twMediaDownloader#45]
Since Twitter's old web media API `/i/profiles/show/:username/media_timeline` was closed, it looks to me the extension now simply use `/1.1/statuses/user_timeline.json` even if downloading Media from a user.

(By the way, for some reason it only uses count=40. I believe they support up to count=200 which may save you some call counts.) 

We probably can improve it by using the new web API `/2/timeline/media/:id.json` as it might be faster for media only requests.

This is just a suggestion; you may have your reason to stick with `user_timeline.json`, so do what you think is the best!

**Comment by furyutei** [comment]
Thanks for your suggestion.

> I believe they support up to count=200 which may save you some call counts.
I'll fix it at the appropriate time.

> new web API /2/timeline/media/:id.json
I don't see a simple parameter (like max_id) to specify the period of time, and it seems to need to be specified with a complex parameter (cursor). 
I haven't been able to analyze the format of the cursor parameter yet. If you know it, please let me know.

**Comment by furyutei** [comment]
This issue has been fixed in [version 0.1.4.14](https://github.com/furyutei/twMediaDownloader/commit/b1a4ae13a2673d06080ea43bfa0c4421561daa0e).

**Comment by fireattack** [comment]
Thanks!
