### ISSUE TITLE
(*) Timeline error: TypeError: Cannot read property 'user_id_str' of undefined

### ISSUE THREAD

**Issue by ee092884** [furyutei/twMediaDownloader#46]
Recently I noticed that some tweets cannot be downloaded
Report an error directly
Most of the tweets can be downloaded
But a few tweets don't work...

One of the tweet URLs that cannot be downloaded：
https://twitter.com/kannonshindo
https://twitter.com/f_una

![image](https://user-images.githubusercontent.com/39590282/92417443-c02f4a80-f194-11ea-8c87-a21f705e3684.png)
![image](https://user-images.githubusercontent.com/39590282/92417393-70508380-f194-11ea-8f4a-a720e257aeb7.png)

**Comment by furyutei** [comment]
Thank you for your report.
I have found the cause of the problem and have fixed it in [version 0.1.4.15](https://github.com/furyutei/twMediaDownloader/commit/c1044ca685a68408ed9655e730089916c111ce79).
