### ISSUE TITLE
If a tweet with video quotes another tweet with images, images from quoted tweet will be downloaded instead

### ISSUE THREAD

**Issue by fireattack** [furyutei/twMediaDownloader#47]
Example: https://twitter.com/mikumoe5th/status/1325027165692260352

**Comment by fireattack** [comment]
If the tweet has images (instead of video), it will download tweet's own image(s) together with quoted image(s).

Example: https://twitter.com/ikenaikoto/status/1325046663975759872

**Comment by furyutei** [comment]
Thank you for reporting this.
It seems to have been a bug caused by a change in Twitter's HTML.
In [version 0.1.4.17](https://github.com/furyutei/twMediaDownloader/commit/14ea2cf895890a3355def2bc891a694eca368926), only the media of the main tweet will be downloaded.
