### ISSUE TITLE
TypeError: Cannot read property 'tweets' of undefined

### ISSUE THREAD

**Issue by thakyZ** [furyutei/twMediaDownloader#53]
All of a sudden the plugin stopped working and I get this error:

```
[twMediaDownloader] (2021-02-26T15:24:01.109Z) https://api.twitter.com/1.1/statuses/show.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&trim_user=false&include_ext_media_color=true&id=1364873363190018051 TypeError: Cannot read property 'tweets' of undefined
    at main_react.user.js:1348 0  
log_error @ main_react.user.js:398
(anonymous) @ main_react.user.js:4384
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
o.<computed> @ jquery.min.js:2
(anonymous) @ main_react.user.js:1353
```

After I click the button to download a video it says that in the console, then also makes an alert that reads "Twitter says: 0". I am not sure why this is happening but I suspect Twitter has updated their code.

**Comment by thakyZ** [comment]
After some looking it appears I am getting this error from the `FETCH_JSON` variable:
```"This request requires a matching csrf cookie and header."```

**Comment by thakyZ** [comment]
Another update I have verified that the CSRF cookie that the extension is using is the same as the one in my browser

**Comment by thakyZ** [comment]
Oh this appears to be a browser issue, when opening links or bookmarks. Works fine if I open the link from within site.

**Comment by thakyZ** [comment]
Okay one last thing, this only appears to affect some video but not all here is an example of one that does work:   
https://twitter.com/CanYouPetTheDog/status/1365319005721010178
And here is an example of one that doesn't work:
https://twitter.com/_TAKUMI928_/status/1364945908224249862

**Comment by fireattack** [comment]
For what it's worth, I can download both videos you linked just fine.

**Comment by thakyZ** [comment]
Yea, it eventually fixed itself I don't know what was happening during that time.
