### ISSUE TITLE
Get video from tweets generated with Twitter for Advertisers tool

### ISSUE THREAD

**Issue by fireattack** [furyutei/twMediaDownloader#54]
Example: https://twitter.com/idolypride/status/1368758376335835140

**Comment by fireattack** [comment]
@furyutei 

Hi, thanks for the update. The newest version works with the above tweet, but not this one: https://twitter.com/idolypride/status/1374662279321509888


After some checking, I think the token you used (`AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA`) doesn't work with some cards, gives this error:

![image](https://user-images.githubusercontent.com/4130991/112400163-bfe04200-8cd5-11eb-81d3-9ced16f9c1cf.png)

This token:
`AAAAAAAAAAAAAAAAAAAAAPYXBAAAAAAACLXUNDekMxqa8h%2F40K4moUkGsoc%3DTYfbDKbT3jJPCEVnMYqilB28NHfOPqkca3qaAxGfsyKCs0wRbw`  (taken from https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/twitter.py#L80 

works with both links:

![image](https://user-images.githubusercontent.com/4130991/112400261-fcac3900-8cd5-11eb-9413-118281f14ae5.png)

**Comment by furyutei** [comment]
I tried changing token as you suggested, but it didn't work in my environment (there may be a difference in API type or account).
I have fixed the problem with a different approach in version 0.1.4.19, please try it.

**Comment by fireattack** [comment]
Thanks, it works now!

**Comment by fireattack** [comment]
@furyutei Sorry for bother you again.

Is it possible to do the similar thing with static images? Such as https://twitter.com/Yahoo_GYAO/status/1374941612896350212

**Comment by furyutei** [comment]
Hmmm... this extension is originally intended for native images only, so there are no plans to support that.

**Comment by fireattack** [comment]
Just to clarify: these /ad_img/ images are actually native, it is manually added in Advertiser tool similarly to the videos mentioned above. It' not related to the URL attached (if you open the URL, you will see it doesn't actually have that image. )

You can get the URL for the media similarly to how you get the video above, from the card info's `string_value` 


![image](https://user-images.githubusercontent.com/4130991/112738538-acc9ae00-8f31-11eb-88cf-57504933fa61.png)

It's _not_ retrieved from target website's `og:image` metadata, which would be /card_img/. Example: https://twitter.com/imas_official/status/1375632493223669763

**Comment by furyutei** [comment]
Sorry, "native" meaning I was referring to was images/videos that can be uploaded by ordinary users.
Please note that media in the card element ([data-testid="card.wrapper"] in HTML (DOM)) is basically unsupported.
I didn't originally intend to support videos from the Advertisers tool, but I added them out of curiosity :)

**Comment by fireattack** [comment]
Understood. 

Thanks for the hard work!
