### ISSUE TITLE
Cannot download: (*) Timeline error: [API] 34: Sorry, that page does not exist

### ISSUE THREAD

**Issue by doio** [furyutei/twMediaDownloader#55]
It seems Twitter has made some changes.

**Comment by furyutei** [comment]
I have updated version 0.1.4.18 today (March 16), so please update your add-ons and give it a try.

**Comment by doio** [comment]
Sorry that I didn't check for updates sooner. The issue has been resolved by updating the add-on, thank you for the hard work. :)
