### ISSUE TITLE
kmozillahelper error on linux

### ISSUE THREAD

**Issue by cglmrfreeman** [furyutei/twMediaDownloader#56]
It appears that when using the batch downloader, something is not properly cleared in linux:

```kf.kio.widgets.kdirmodel: No node found for item that was just removed: QUrl("file://[location removed].zip")```

This error appears many times in my system log files.

**Comment by cglmrfreeman** [comment]
Any updates? This is very annoying.
![Screenshot_20210324_170321](https://user-images.githubusercontent.com/9744201/112399125-e34dc180-8cc2-11eb-86f0-7f8afd5459fc.png)

**Comment by furyutei** [comment]
There is no such thing as a recent change in the way zip files are saved (and nothing was changed in the period March 16 - March 26).
This is probably a problem specific to Linux (KDE), but I can't do anything about it because I don't have an environment in which I can reproduce it.

**Comment by cglmrfreeman** [comment]
This is apparently a KDE issue, not specific to twMediaDownloader or kmozillahelper. Closing.
