### ISSUE TITLE
ユーザー名が絵文字のみの時メディアや「いいね」の一括ダウンロードボタンが表示されない

### ISSUE THREAD

**Issue by eulpnu** [furyutei/twMediaDownloader#59]
ChromeとFirefoxの拡張機能版を使っています。
ユーザー名が絵文字のみのユーザーのページで一括ダウンロードボタンが表示されなくなっているようです。
❔のみの場合と🙂のみの場合で確認しました。
一括ダウンロードボタンが表示できているユーザーのページから検索欄のサジェストなどを利用して「ユーザー名が絵文字のみのユーザー」のページへと遷移すると一時的に表示できるようです。

**Comment by furyutei** [comment]
[0.1.4.22](https://github.com/furyutei/twMediaDownloader/commit/e8616f5d3833f933c159a9305b66653f65a9a60d)で対応しましたのでご確認願います。

**Comment by eulpnu** [comment]
0.1.4.22で表示されました。素早く対応していただきありがとうございます。
