### ISSUE TITLE
Bug - Twitter Video Downloads Appear to be broken

### ISSUE THREAD

**Issue by ShawnNogi** [furyutei/twMediaDownloader#60]
Alt-Click and normal downloading of videos appear to be broken with the error

"twitter.com says [object Object]  "

**Comment by furyutei** [comment]
I'm unable to reproduce the problem in my environment.
Please tell me exactly what environment you are using (OS, browser, extension version) and the tweet that causes the error.

**Comment by ShawnNogi** [comment]
Windows 10
Twitter Media Downloader ( version 0.1.4.23 )
I've tried in Edge, Chrome, and Brave.
![brave_7yEL5eQtLl](https://user-images.githubusercontent.com/39767738/124281329-9c6c3500-db17-11eb-9799-1fd8115441ef.png)
![chrome_9bP4r5KeQJ](https://user-images.githubusercontent.com/39767738/124281354-a2621600-db17-11eb-9b57-542e50544e24.png)
![msedge_A8CWZSbCJg](https://user-images.githubusercontent.com/39767738/124281370-a5f59d00-db17-11eb-8231-19ada36f1fe9.png)

**Comment by furyutei** [comment]
Please be logged in to Twitter.
This extension does not support operation in the unlogged state.

**Comment by ShawnNogi** [comment]
That's unfortunate. From a privacy aspect I don't want to create a twitter account.
