### ISSUE TITLE
Download button not showing

### ISSUE THREAD

**Issue by pjrfigueiredo** [furyutei/twMediaDownloader#62]
Download button isn't being displayed.

**Comment by Oyami-Srk** [comment]
seems like another twitter upgrade happend...

**Comment by pjrfigueiredo** [comment]
>                 (0 < $tweet.find('div[data-testid="tweet"]').length || true) && // overrided true statement
>                 (0 < $tweet.find('div[aria-label]').length || true) && // like above

It worked. Thanks!

Amazing extension!

**Comment by GiovanH** [comment]
Can confirm. Hopefully that patch can be applied soon.

**Comment by tentedpgh** [comment]
> Seems like another twitter upgrade happend...
> You can patch `src/js/main_react.user.js` at line 4620 like:
> 
> ```js
>     $tweets = $node
>         //.find( 'div[data-testid="primaryColumn"] article[role="article"]:has(div[data-testid="tweet"]):has(div[aria-label]):not(:has(.' + SCRIPT_NAME + '_media_button))' ) // → :has() を使わなくしてもそれ程パフォーマンスは変わらない
>         .find( 'div[data-testid="primaryColumn"] article[role="article"]' )
>         .filter( function () {
>             var $tweet = $( this );
>             
>             return (
>                 ( ! $tweet.hasClass( SCRIPT_NAME + '_touched' ) ) &&
>                 (0 < $tweet.find('div[data-testid="tweet"]').length || true) && // overrided true statement
>                 (0 < $tweet.find('div[aria-label]').length || true) && // like above
>                 ( $tweet.find( '.' + SCRIPT_NAME + '_media_button' ).length <= 0 ) &&
>                 ( $tweet.find( 'a.' + SCRIPT_NAME + '_tweet_profile' ).length <= 0 )
>             );
>         } );
> ```
> 
> I am not sure about the safety, use at your own risk. ( Inserting a element without checking may cause earth explosion lol )
> Twitter now has no fine-tagged `div` elements inside tweets `article`.

How do you add that? where is the file? thank you!

**Comment by Oyami-Srk** [comment]
> > Seems like another twitter upgrade happend...
> > You can patch `src/js/main_react.user.js` at line 4620 like:
> > ```js
> >     $tweets = $node
> >         //.find( 'div[data-testid="primaryColumn"] article[role="article"]:has(div[data-testid="tweet"]):has(div[aria-label]):not(:has(.' + SCRIPT_NAME + '_media_button))' ) // → :has() を使わなくしてもそれ程パフォーマンスは変わらない
> >         .find( 'div[data-testid="primaryColumn"] article[role="article"]' )
> >         .filter( function () {
> >             var $tweet = $( this );
> >             
> >             return (
> >                 ( ! $tweet.hasClass( SCRIPT_NAME + '_touched' ) ) &&
> >                 (0 < $tweet.find('div[data-testid="tweet"]').length || true) && // overrided true statement
> >                 (0 < $tweet.find('div[aria-label]').length || true) && // like above
> >                 ( $tweet.find( '.' + SCRIPT_NAME + '_media_button' ).length <= 0 ) &&
> >                 ( $tweet.find( 'a.' + SCRIPT_NAME + '_tweet_profile' ).length <= 0 )
> >             );
> >         } );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am not sure about the safety, use at your own risk. ( Inserting a element without checking may cause earth explosion lol )
> > Twitter now has no fine-tagged `div` elements inside tweets `article`.
> 
> How do you add that? where is the file? thank you!

Download source files on [github](https://github.com/furyutei/twMediaDownloader/archive/refs/heads/master.zip). Unzip it and modify file `src/js/main_react.user.js`. Then goto folder `src`, copy `manifest-chrome.json` or `manifest-firefox` to `manifest.json`(override the original one) depending on your platform. Then disable original extension and load unzipped extension from `src` folder.

This patch is only a temporary workaround.

**Comment by tentedpgh** [comment]
> > > Seems like another twitter upgrade happend...
> > > You can patch `src/js/main_react.user.js` at line 4620 like:
> > > ```js
> > >     $tweets = $node
> > >         //.find( 'div[data-testid="primaryColumn"] article[role="article"]:has(div[data-testid="tweet"]):has(div[aria-label]):not(:has(.' + SCRIPT_NAME + '_media_button))' ) // → :has() を使わなくしてもそれ程パフォーマンスは変わらない
> > >         .find( 'div[data-testid="primaryColumn"] article[role="article"]' )
> > >         .filter( function () {
> > >             var $tweet = $( this );
> > >             
> > >             return (
> > >                 ( ! $tweet.hasClass( SCRIPT_NAME + '_touched' ) ) &&
> > >                 (0 < $tweet.find('div[data-testid="tweet"]').length || true) && // overrided true statement
> > >                 (0 < $tweet.find('div[aria-label]').length || true) && // like above
> > >                 ( $tweet.find( '.' + SCRIPT_NAME + '_media_button' ).length <= 0 ) &&
> > >                 ( $tweet.find( 'a.' + SCRIPT_NAME + '_tweet_profile' ).length <= 0 )
> > >             );
> > >         } );
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I am not sure about the safety, use at your own risk. ( Inserting a element without checking may cause earth explosion lol )
> > > Twitter now has no fine-tagged `div` elements inside tweets `article`.
> > 
> > 
> > How do you add that? where is the file? thank you!
> 
> It has been fixed on the version `0.1.4.25`.

Thank you!
