### ISSUE TITLE
Extension no longer working after new Twitter update

### ISSUE THREAD

**Issue by havingfun2500** [furyutei/twMediaDownloader#64]
It seems that the extension no longer works after a recent Twitter update. I was still able to use the extension yesterday but now when I visit a profile there is no button to download media at all.

**Comment by Explorare** [comment]
Works on Firefox Dev 93.0b9 (64-bit) with plugin 0.1.4.25.

**Comment by havingfun2500** [comment]
I checked again today and it seems to be working normally now.

**Comment by havingfun2500** [comment]
I found the reason. I was using a mobile.twitter.com link so the extension didn't recognize it.
