### ISSUE TITLE
[Feature Request] Support for Twitter Moments/Events?

### ISSUE THREAD

**Issue by biggestsonicfan** [furyutei/twMediaDownloader#69]
Twitter allows users to create Moments or Events which is a sub-timeline made up of a user's individually selected tweets. Here is one of mine for [example](https://twitter.com/i/events/1398142725581533186). It would be nice to use twMediaDownloader on some of these curated lists!

**Comment by 06000208** [comment]
I would really appreciate this.

**Comment by cglmrfreeman** [comment]
I was using gallery-dl because they implemented it very quickly, but twitter now requires authentication for sensitive media and you can't use gallery-d with 2fa, so this would be very nice to have for twMediaDownloader

**Comment by biggestsonicfan** [comment]
Since Twitter has removed new moment/events going forward, I may as well close this as a wontfix.
