### ISSUE TITLE
twMediaDownloader does not download non-original when original fails

### ISSUE THREAD

**Issue by cglmrfreeman** [furyutei/twMediaDownloader#70]
Looking at this tweet [here](https://twitter.com/gonzarez1938/status/1478387067881422853), twitter can not load the large or orig image. Attempting to download the file with twMediaDownloader results in a 22 byte blank zip file.

I wonder how many images have simply been skipped in my archives because it did not fallback to a valid image before downloading.

**Comment by fireattack** [comment]
It's a twitter server problem. Sometimes image URL will return HTTP 503.
