### ISSUE TITLE
Would you like to support text tweet, not just only media?

### ISSUE THREAD

**Issue by menduo** [furyutei/twMediaDownloader#77]
Thanks

**Comment by Explorare** [comment]
![image](https://user-images.githubusercontent.com/5090766/168534587-a340fba3-841f-4c01-b074-d577ada2685d.png)
There is an option to includes non-media tweet. Is this the function you need?

**Comment by menduo** [comment]
Got it. Thanks a lot.

**Comment by menduo** [comment]
Maybe the option should be named as 'text without media' ?
