### ISSUE TITLE
Could not download the ZIP file in Private Browsing: "ZIP_GENERATE: XMLHttpRequest() error: 0"

### ISSUE THREAD

**Issue by lss4** [furyutei/twMediaDownloader#8]
I'm on latest Manjaro Linux with Firefox 58 64-bit. After finishing download the zip file download does not appear.

When I use F12 to inspect, I found the following two errors in the console:
ZIP_GENERATE: XMLHttpRequest() error: 0
zip_request_legacy.js:146:9
ZipRequestLegacy.prototype.__error__
moz-extension://f9a3781d-839a-42b0-aa01-5a113641a9b7/js/zip_request_legacy.js:146:9
ZipRequestLegacy.prototype.__flush__/</xhr.onerror
moz-extension://f9a3781d-839a-42b0-aa01-5a113641a9b7/js/zip_request_legacy.js:255:25

[twMediaDownloader] (2018-03-01T02:44:48.771Z) zip_request.generate() error: 0
twMediaDownloader.user.js:248:5
log_error
moz-extension://f9a3781d-839a-42b0-aa01-5a113641a9b7/js/twMediaDownloader.user.js:248:5
start_download/request_save/<
moz-extension://f9a3781d-839a-42b0-aa01-5a113641a9b7/js/twMediaDownloader.user.js:2450:33
ZipRequestLegacy.prototype.__error__
moz-extension://f9a3781d-839a-42b0-aa01-5a113641a9b7/js/zip_request_legacy.js:151:13
ZipRequestLegacy.prototype.__flush__/</xhr.onerror
moz-extension://f9a3781d-839a-42b0-aa01-5a113641a9b7/js/zip_request_legacy.js:255:25

EDIT 2: It appears the extension does not work with Private Browsing. I was able to generate and download the ZIP file when I ran it on a normal Firefox window, and the settings are kept there.

With Private Browsing, the above error occurs when generating the ZIP file, and the settings are not kept.

I'm not using Chrome at present, but I presume Incognito mode might also be affected.

**Comment by furyutei** [comment]
Thank you for your detailed report.
In Firefox, I also confirmed that the download failed on incognito window.
I implemented countermeasures with version 0.1.1.2201.
https://github.com/furyutei/twMediaDownloader/commit/bdedea8b5e07b17730a02ac29a3b626f88e6004f

For Chrome,
https://github.com/furyutei/twMediaDownloader/issues/4
The measures have been taken.

**Comment by lss4** [comment]
I can confirm that the download now works in Firefox private browsing now.
However, it still appears that settings cannot be applied or saved under private browsing. It has no effect and the settings made would automatically revert. For example, after setting the size limit higher than 500MB, the download process still stops once hitting 500MB and when that happens, opening the settings pane would find the download size reverted to default along with other settings.

**Comment by furyutei** [comment]
I created [a new issue](https://github.com/furyutei/twMediaDownloader/issues/9) about it.
