### ISSUE TITLE
デベロッパーモードで動作しているManifest V3対応版がChrome Web Storeにアップロードすると動かなくなる

### ISSUE THREAD

**Issue by furyutei** [furyutei/twMediaDownloader#89]
Manifest V3に対応した[こちらの版](https://github.com/furyutei/twMediaDownloader/tree/067e0d51a23fe958ed3d87a5c48fc8d045f9988c)が、  
Google Chrome バージョン: 105.0.5195.127（Official Build） （64 ビット）  
のデベロッパーモードで「パッケージ化されていない拡張機能を読み込む」から読み込んだ場合は普通に動くのですが、同じファイルをZIP化したものをChrome Web Storeにアップロード後インストールすると、まったく動作しなくなります。  
※[「Service Worker （無効）」となってしまい、ビューを検証もできません](https://twitter.com/furyutei/status/1575135811191721984)  
※また、[インストール時に作成されたフォルダ（%LOCALAPPDATA%\Google\Chrome\User Data\Default\Extensions\cblpjenafgeohmnjknfhpdbdljfkndig\0.1.5.0_0）の内容を別の場所にコピーし、「パッケージ化されていない拡張機能を読み込む」と、正常に動きます](https://twitter.com/furyutei/status/1575150947365715968)    

正直お手上げなのですが、なにか解決するためのヒントなりご存じの方いらっしゃいませんか？

**Comment by cute-angelia** [comment]
add background-wrapper.js importScripts background.js

```
  # manifest.json
  "background": {
    "service_worker": "background-wrapper.js" // !!!! must root path !!!!
  },


  # background-wrapper.js

  try {
    importScripts("background.entry.js");  // replace your background.js
  } catch (e) {
    console.error(e);
  }

```

**Comment by furyutei** [comment]
> add background-wrapper.js importScripts background.js

Thank you!
This allowed me to pinpoint the cause and make [the extension compatible with Manifest V3](https://github.com/furyutei/twMediaDownloader/commit/709b26525850f0f1936b96dae0b468a978361ede).

Oddly enough, only when installed from the Chrome Web Store,
chrome.declarativeNetRequest.onRuleMatchedDebug
was undefined...

**Comment by fireattack** [comment]
V3 version seems to be a little bit slower than V2 when downloading a single tweet, but it's a minor issue.
